spring:
    datasource:
        url: jdbc:mysql://127.0.0.1/dev?serverTimezone=GMT%2B8
        username: root
        password: 123456
logging:
    level:
        com.example.lsbcrudplus.mapper.UserMapper: debug # 改成你的mapper文件所在包路径