
logging:
  level:
    com:
      example:
        lsbdigui:
          mapper: debug
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dev?serverTimezone=GMT%2B8
    username: root
    password: 123456
server:
  port: 8081

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl